#!/bin/sh

BASEDIR=$(dirname "$0")

rm -rf $BASEDIR/../target
mkdir -p $BASEDIR/../target

(
  cd $BASEDIR/../
  mvn assembly:assembly
  cp target/query-0.0.1-SNAPSHOT-jar-with-dependencies.jar target/query.jar
)
