#!/bin/sh


BASEDIR=$(dirname "$0")

hbase shell $BASEDIR/rebuild_tables

hbase org.apache.hadoop.hbase.mapreduce.ImportTsv -Dimporttsv.separator=":" -Dimporttsv.columns=HBASE_ROW_KEY,title "s103062512:map" $1/map
hbase org.apache.hadoop.hbase.mapreduce.ImportTsv -Dimporttsv.separator=":" -Dimporttsv.columns=HBASE_ROW_KEY,docfreq,occurrences "s103062512:invertedindex" $1/index
hbase org.apache.hadoop.hbase.mapreduce.ImportTsv -Dimporttsv.separator=":" -Dimporttsv.columns=HBASE_ROW_KEY,score "s103062512:pagerank" $1/rank
