#!/bin/sh

BASEDIR=$(dirname "$0")

hdfs dfs -rm -r -f $2

spark-submit --class preprocess.Worker --num-executors 30 $BASEDIR/../target/spark.jar $1 $2/raw
spark-submit --class index.Worker --num-executors 30 $BASEDIR/../target/spark.jar $2/raw $2/index
